# Generated by Django 5.2.17 on 2026-10-04 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ExpeditionsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delai_jours', models.PositiveIntegerField()),
                ('prix', models.DecimalField(decimal_places=100, max_digits=100)),
                ('statut', models.CharField(choices=[('proposee', 'Proposee'), ('acceptee', 'Acceptee'), ('refusee', 'Refusee'), ('retiree', 'Retiree')], default='proposee', max_length=100)),
                ('Date_proposition', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpeditionsApp.expeditions')),
            ],
        ),
    ]
