# Generated by Django 5.2.17 on 2026-10-04 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0001_initial'),
        ('ExpeditionsApp', '0001_initial'),
        ('OffresApp', '0001_initial'),
        ('VehiculeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delai_jours', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('proposee', 'Proposee'), ('acceptee', 'Acceptee'), ('refusee', 'Refusee'), ('retiree', 'Retiree')], default='proposee', max_length=20)),
                ('date_proposition', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpeditionsApp.expeditions')),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EntrepriseApp.entreprise')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VehiculeApp.vehicule')),
            ],
        ),
        migrations.DeleteModel(
            name='Offres',
        ),
    ]
