# Generated by Django 5.2.17 on 2026-10-04 17:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expeditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=uuid.uuid4, max_length=200, unique=True)),
                ('poids_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('publiee', 'Publiee'), ('attribuee', 'Attribuee'), ('en_cours', 'En cours'), ('annulee', 'Annulee'), ('livree', 'Livree')], default='publiee', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EntrepriseApp.entreprise')),
            ],
        ),
    ]
