# Generated by Django 5.2.17 on 2026-10-10 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0002_entreprise_id_alter_entreprise_adresse_and_more'),
        ('ExpeditionsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expeditions',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='EntrepriseApp.entreprise'),
        ),
    ]
