# Generated by Django 5.2.17 on 2026-10-10 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpeditionsApp', '0002_alter_expeditions_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expeditions',
            name='poids_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='expeditions',
            name='reference',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
