# Generated by Django 5.2.17 on 2026-10-10 20:51

import EntrepriseApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, 'L adresse doit contenir au moins 20 caracteres')]),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='matricule_fiscale',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Format attendu : 7 chiffres , 1 lettre (cle de controle) , 1 lettre(A/B/D/N/P) , 1 lettre (M/P/C/N/E) , 3 chiffres', regex='^\\d{7}[/ -]?[A-Za-z][/ -]?[ABDNPEadbnpe][/ -]?[MPCNEmpcne][/ -]?\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[EntrepriseApp.models.validate_email]),
        ),
    ]
