# Generated by Django 5.2.17 on 2026-10-10 23:35

import EntrepriseApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0002_entreprise_id_alter_entreprise_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, 'L adresse doit contenir au moins 20 caracteres'), EntrepriseApp.models.emailvalidator]),
        ),
    ]
