# Generated by Django 5.2.17 on 2026-10-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiculeApp', '0002_alter_vehicule_capacite_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='type_vehicule',
            field=models.CharField(blank=True, choices=[('camionnette', 'Camionnette / utilitaire léger'), ('camion_porteur', 'Camion porteur'), ('semi_remorque', 'Semi-remorque'), ('fourgon', 'Fourgon')], max_length=30, null=True),
        ),
    ]
